### ISSUE TITLE
Error with grub during installation

### ISSUE THREAD

**Issue by allezacc** [olm3ca/Pixelbook-Campfire#1]
Hi, when trying to install chromeos from terminal in mint Linux I get an error after I choose my installation partition that says "error while loading the grub list" that doesn't let me proceed with the installation. Thanks for your time in this project.

**Comment by olm3ca** [comment]
Yes - that error is expected, as the script was written for PCs and not Chromebooks. In our case, all that matters is the grub config text right above that error, it should be there, and it should resemble the text on the readme which I have provided.

If so, copy that and save it anywhere (in a Windows folder, or on a USB stick). Then reboot into Windows and add that text to grub2win as a custom code entry. And make sure you edit the grub config as described in the readme.

**Comment by allezacc** [comment]
Oh I got it to work, thanks a lot!
