### ISSUE TITLE
Headphone jack doesn't work on Brunch

### ISSUE THREAD

**Issue by insertwittyusername** [olm3ca/Pixelbook-Campfire#2]
Only the speakers work, if I plug in headphones, it detects it and switches to absolute maximum volume coming out of the speakers still. Unplug the headphones, it goes back to normal volume. But I can't get it to output over 3.5 mm either way. The speakers work flawlessly though.

**Comment by olm3ca** [comment]
So that's interesting. It used to work fine. Are you on 90? I have the exact same issue on the Galaxy Chromebook. Wonder if it's related.

**Comment by insertwittyusername** [comment]
Yes, I'm on 90. Updated to it after installing from the 87 recovery .bin.

**Comment by olm3ca** [comment]
Wondering if it's something 90 related then. It used to work. You could ping sebanc on Brunch discord, sadly I don't have any way to fix it

**Comment by insertwittyusername** [comment]
Okay, for the time being I think I'll reinstall on 89. Thanks for the lead.
