### ISSUE TITLE
ChromeOS Network fail when using brunch unstable 

### ISSUE THREAD

**Issue by sitam70** [olm3ca/Pixelbook-Campfire#3]
Hi olm3ca

I had followed your guide and had using the latest pixel book chromeos recovery image. Problem i'm facing now is there will be no network available if restored using unstabe brunch version. But if I'm using latest stable brunch and using your customize script for grub2win cromeos can run and setup succeccfully. The only problem is the network/wifi will disappear after sleep. Even wil can be worse it will reset the log-in and reset the user's profile.

Any suggestion to solve the problem?

Thank you and regards.
sitam

**Comment by olm3ca** [comment]
That's interesting. You can actually replace the wifi driver fairly easily - if you look at my repo for the Galaxy Chromebook there are instructions on how to do it. I would try reverting to an older wifi driver from an earlier CrOS build and see if that fixes it.
